"""Add password_reminder column to users

Revision ID: 0f0872a13a81
Revises: c6580c5f546e
Create Date: 2025-02-15 18:30:32.328627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0872a13a81'
down_revision: Union[str, None] = 'c6580c5f546e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reminder', sa.String(length=255), nullable=False))
    op.create_unique_constraint('uq_email', 'users', ['email'])
    op.create_unique_constraint('uq_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_username', 'users', type_='unique')
    op.drop_constraint('uq_email', 'users', type_='unique')
    op.drop_column('users', 'password_reminder')
    # ### end Alembic commands ###
