"""Add is_published to posts

Revision ID: 2007696b5adc
Revises: c1f4897a9084
Create Date: 2025-01-27 18:35:36.350853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2007696b5adc'
down_revision: Union[str, None] = 'c1f4897a9084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_published')
    # ### end Alembic commands ###
