"""Add unique constraint on ratings (post_id, user_id)

Revision ID: c6580c5f546e
Revises: c0240196d484
Create Date: 2025-02-15 16:24:50.504573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6580c5f546e'
down_revision: Union[str, None] = 'c0240196d484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_post_user_rating', 'ratings', ['post_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_post_user_rating', 'ratings', type_='unique')
    # ### end Alembic commands ###
